#!/bin/sh
set -euf
unset IFS
sudo dpkg --add-architecture armhf
sudo apt-get update \
    --allow-releaseinfo-change # Work around https://github.com/mcandre/packer-templates/issues/251
sudo apt-get install -y \
    qemu-user-static \
    g++-arm-linux-gnueabihf \
    libc6:armhf \
    libstdc++6:armhf
sudo apt-get autoclean -y
sudo apt-get clean -y
sudo rm -rf /var/lib/apt/lists/* \
    /var/cache/apt/pkgcache.bin \
    /var/cache/apt/srcpkgcache.bin
